kids_website/games/urls.py
from django.conf.urls import url
from . import views

app_name = 'games'

urlpatterns = [
    # Games main page
    url(r'^$', views.games, name='games'),

    # Math game
    url(r'^math/$', views.math, name='math'),

    # English game
    url(r'^english/$', views.games, name='english'),

    # Hgih scores
    url(r'^highscores/(?P<game_id>\d+)/$', views.high_scores, name='highscores'),
]

kids_website/kids_website/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Home / profile
    url(r'^', include('Profile.urls')),

    # Games
    url(r'^games/', include('games.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kids_website/games/models.py
from django.db import models
from django.contrib.auth.models import User


class Game(models.Model):
    url = models.CharField(max_length=64, unique=True)
    name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Score(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    value = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username + ' - ' + self.game.name

kids_website/games/views.py
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Max
from Profile.views import verified
from .models import Game, Score
from random import randint, shuffle


@verified
def games(request):
    allgames = Game.objects.all()
    return render(request, 'games/games.html', {'games': allgames})


@verified
def math(request):
    user = request.user
    game_name = 'Math game'
    game = Game.objects.get(name=game_name)

    context = {}

    try:
        score = user.score_set.get(game=game)
    except ObjectDoesNotExist:
        score = Score(user=user, game=game)
        score.save()

    context['game'] = game
    context['score'] = score

    if request.method == 'POST':
        result = request.POST.get('answer')
        print(repr(result))
        print(repr(request.session['answer']))
        if result == request.session['answer']:
            score.value += 1
            score.save()
            context['success'] = True
        else:
            context['failure'] = True

    # Generate new values
    con, result = generate_math()
    request.session['answer'] = str(result)

    context.update(con)
    context.update(game.score_set.all().aggregate(Max('value')))
    return render(request, 'games/math.html', context)


def generate_math():
    context = {}

    val1 = randint(1, 20)
    val2 = randint(1, 20)

    operation = randint(0, 2)

    if operation == 0:
        context['operator'] = '+'
        val3 = val1 + val2
    elif operation == 1:
        if val1 < val2:
            val1, val2 = val2, val1
        context['operator'] = '-'
        val3 = val1 - val2
    else:
        context['operator'] = 'x'
        val3 = val1 * val2

    context['val1'] = val1
    context['val3'] = val3

    # generate false answers
    l = [randint(1, 20), randint(1, 20)]
    while val2 in l or l[0] == l[1]:
        if l[0] == val2:
            l[0] = randint(1, 20)
        elif l[1] == val2:
            l[1] = randint(1, 20)
        else:
            l[0] = randint(1, 20)

    l += [val2]
    shuffle(l)

    context['ans1'], context['ans2'], context['ans3'] = l

    return context, val2


@verified
def high_scores(request, game_id):
    game = get_object_or_404(Game, pk=game_id)

    # Top 50
    scores = game.score_set.order_by('-value')[:50]
    return render(request, 'games/highscores.html', {'game': game, 'scores': scores})

kids_website/games/templates/games/base_game.html
{% extends 'Profile/base_user.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3 class="mark" title='{{ game.description }}'>{{ game.name }}</h3>
                {% block play %}
                {% endblock %}
            </div>

            <div class="cold-md-4">
                <h3 class="mark col-md-1">Score:</h3>
                <h3 class="mark text-right col-md-3">{{ score.value }}</h3>

                <a href="{% url 'games:highscores' game.id %}">
                    <h3 class="mark col-md-2">Highscore:</h3>
                    <h3 class="mark text-right col-md-2">{{ value__max }}</h3>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

kids_website/games/templates/games/games.html
{% extends 'Profile/base_user.html' %}

{% block content %}
    <div class="container">
        <p>Games</p>
        <ul>
            {% for game in games %}
                <li><a href={{ game.url }}>{{ game.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

kids_website/games/templates/games/highscores.html
{% extends 'Profile/base_user.html' %}

{% block content %}
    <div class="container">
        <h1>Highscores of {{ game.name }}</h1>
        <br>
        <table class="table table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Score</th>
                </tr>
            </thead>
            <tbody>
                {% for score in scores %}
                    <tr>
                        <td>{{ score.user.username }}</td>
                        <td>{{ score.value }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

kids_website/games/templates/games/math.html
{% extends 'games/base_game.html' %}

{% block play %}
    <div class="container">
        <h2>Choose the right number.</h2>
        <div class="text-center">
            <form class="form-inline" autocomplete="off" action="" method="post">
                {% csrf_token %}
                <div class="form-group row">
                    <p class="form-control col-md-1">{{ val1 }}</p>
                    <p class="form-control col-md-1" style="width: 35px;">{{ operator }}</p>
                    <input class="form-control col-md-1" maxlength="1" style="width: 35px;" name="" disabled="disabled">
                    <p class="form-control col-md-1">=</p>
                    <p class="form-control col-md-1">{{ val3 }}</p>
                </div>

                <div class="row">
                    <button class="btn btn-info" type="submit" name="answer" value="{{ ans1 }}">{{ ans1 }}</button>
                    <button class="btn btn-info" type="submit" name="answer" value="{{ ans2 }}">{{ ans2 }}</button>
                    <button class="btn btn-info" type="submit" name="answer" value="{{ ans3 }}">{{ ans3 }}</button>
                </div>
            </form>

            {% if success %}
            <p class="text-success" style="margin-top: 20px"><span class="glyphicon glyphicon-ok"></span> Good Job.</p>
            {% elif failure %}
            <p class="text-danger" style="margin-top: 20px"><span class="glyphicon glyphicon-remove"></span> Wrong answer.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}