kids_website/Profile/urls.py
from django.conf.urls import url
from . import views

app_name = 'Profile'

urlpatterns = [
    # Home / profile
    url(r'^$', views.index, name='index'),

    # Register
    url(r'^register/$', views.register, name='register'),

    # Login
    url(r'^login/$', views.log_in, name='login'),

    # Settings
    url(r'^settings/$', views.settings, name='settings'),

    # Logout
    url(r'^logout/$', views.log_out, name='logout'),
]

kids_website/games/urls.py
from django.conf.urls import url
from . import views

app_name = 'games'

urlpatterns = [
    # Games main page
    url(r'^$', views.games, name='games'),

    # Math game
    url(r'^math/$', views.math, name='math'),

    # English game
    url(r'^english/$', views.games, name='english'),

    # Hgih scores
    url(r'^highscores/(?P<game_id>\d+)/$', views.high_scores, name='highscores'),
]

kids_website/kids_website/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Home / profile
    url(r'^', include('Profile.urls')),

    # Games
    url(r'^games/', include('games.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kids_website/Profile/models.py
from django.db import models
from django.contrib.auth.models import User


class Picture(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    image = models.ImageField(upload_to='media' + '' + '/')

    def __str__(self):
        return self.image.name

kids_website/games/models.py
from django.db import models
from django.contrib.auth.models import User


class Game(models.Model):
    url = models.CharField(max_length=64, unique=True)
    name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Score(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    value = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username + ' - ' + self.game.name

kids_website/Profile/forms.py
from django.contrib.auth.models import User
from django import forms
import re


NAME_RE = re.compile(r'^[a-zA-z]+$')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'email']


class SettingsForm(forms.Form):
    first_name = forms.CharField(label='Change first name', required=False)
    last_name = forms.CharField(label='Change last name', required=False)
    image = forms.ImageField(label='Change profile picture', required=False)

    def clean_name(self, field):
        data = self.cleaned_data.get(field)

        if data and not NAME_RE.match(data):
            raise forms.ValidationError('Name can contain only letters.')

        return data

    def clean_first_name(self):
        return self.clean_name('first_name')

    def clean_last_name(self):
        return self.clean_name('last_name')

    def clean_image(self):
        data = self.cleaned_data['image']

        if data and data._size > 5242880:
            raise forms.ValidationError('Maximum size is 5MB.')

        return data

kids_website/Profile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from .forms import UserForm, SettingsForm
from .models import Picture
from functools import wraps
import re
import os


# Regular Expressions
UNAME_RE = re.compile(r'^[0-9a-zA-z_-]+$')
EMAIL_RE = re.compile(r'^[0-9a-zA-z_-]+@[a-zA-Z0-9]([a-zA-Z0-9-]*\.)+[a-z]{2,}$')


# Session check decorators
def verified(func):
    @wraps(func)
    def inner(request, *args, **kwargs):
        if request.user.is_authenticated():
            return func(request, *args, **kwargs)
        else:
            return redirect('Profile:index')
    return inner


def notverified(func):
    @wraps(func)
    def inner(request, *args, **kwargs):
        if not request.user.is_authenticated():
            return func(request, *args, **kwargs)
        else:
            return redirect('Profile:index')
    return inner


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'Profile/home.html', {'title': 'Complec City'})
    return render(request, 'Profile/profile.html')


@notverified
def register(request):
    if request.method == 'POST':
        post = request.POST

        # Check form fields
        context = invalid_data(post)
        if context:
            return render(request, 'Profile/register.html', context)

        # Create user and redirect to Profile
        return create_user(request, post)

    return render(request, 'Profile/register.html', {'title': 'Register an account'})


def invalid_data(post):
    context = {'title': 'Register an account'}
    # fields
    username = UNAME_RE.match(post.get('username'))
    email = EMAIL_RE.match(post.get('email'))
    password = post.get('password')
    confirm = post.get('confirmpass')

    flag = False

    if username:
        try:
            username = username.group()
            User.objects.get(username=username)
            flag = True
            context['invalid_user'] = 'Username is already registered'
        except ObjectDoesNotExist:
            context['username'] = username
    else:
        flag = True
        context['invalid_user'] = 'Invaled username'

    if email:
        try:
            email = email.group()
            User.objects.get(email=email)
            flag = True
            context['invalid_email'] = 'Email is already registered'
        except ObjectDoesNotExist:
            context['email'] = email
    else:
        flag = True
        context['invalid_email'] = 'Invaled email'

    if len(password) < 8:
        flag = True
        context['shortpassword'] = True

    if password != confirm:
        flag = True
        context['missmatch'] = True

    if flag:
        return context
    return False


def create_user(request, post):
    form = UserForm(post)
    if form.is_valid():
        user = form.save(commit=False)

        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        user.set_password(password)

        user.save()

        user = authenticate(username=username, password=password)

        if user and user.is_active:
            login(request, user)
            return redirect('Profile:index')
    return render(request, 'Profile/register.html', {'title': 'Register an account'})


@notverified
def log_in(request):
    context = {'title': 'Log in'}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        ip = request.META.get('REMOTE_ADDR')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect('Profile:index')
            else:
                context['message'] = 'Account is disabled.'
        else:
            context['message'] = 'Invalid username or password.'
            context['username'] = username

    return render(request, 'Profile/login.html', context)


@verified
def log_out(request):
    logout(request)
    return redirect('Profile:index')


@verified
def settings(request):
    if request.method == 'POST':
        form = SettingsForm(request.POST, request.FILES)

        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            image = form.cleaned_data['image']

            user = request.user

            if first_name:
                user.first_name = first_name.lower().capitalize()
            if last_name:
                user.last_name = last_name.lower().capitalize()
            if image:
                fname = 'media/' + user.username + os.path.splitext(image.name)[1]
                save_image(fname, image)

                try:
                    picture = user.picture
                except ObjectDoesNotExist:
                    user.picture = Picture(user=user)
                    picture = user.picture

                picture.image = fname
                picture.save()

            user.save()
            return redirect('Profile:index')
    else:
        form = SettingsForm()

    return render(request, 'Profile/settings.html', {'form': form})


def save_image(name, f):
    with open(name, 'wb') as fp:
        for chunk in f.chunks():
            fp.write(chunk)

kids_website/Profile/templates/Profile/base_guest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles%}
    <link rel="stylesheet" type="text/css" href={% static 'Profile/css/bootstrap.min.css' %}>
    <script type="text/javascript" src={% static 'Profile/js/jquery-3.1.1.min.js' %}></script>
	<script type="text/javascript" src={% static 'Profile/js/bootstrap.min.js' %}></script>
    <style>
        .navbar{border-radius: 0px;}
    </style>
    <script type="text/javascript">
		$(function(){
	    $(".dropdown").hover(
	            function() {
	                $('.dropdown-menu', this).stop( true, true ).fadeIn("fast");
	                $(this).toggleClass('open');
	                $('b', this).toggleClass("caret caret-up");
	            },
	            function() {
	                $('.dropdown-menu', this).stop( true, true ).fadeOut("fast");
	                $(this).toggleClass('open');
	                $('b', this).toggleClass("caret caret-up");
	            });
	    });
	</script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div>
            <!-- left part -->
            <ul class="nav navbar-nav">
                <li><a href={% url 'Profile:index' %}><span class="glyphicon glyphicon-home"></span> Home</a></li>
                <li><a href={% url 'Profile:login' %}>Login</a></li>
                <li><a href={% url 'Profile:register' %}>Register</a></li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

kids_website/Profile/templates/Profile/base_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ user.username }}</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles%}
    <link rel="stylesheet" type="text/css" href={% static 'Profile/css/bootstrap.min.css' %}>
    <script type="text/javascript" src={% static 'Profile/js/jquery-3.1.1.min.js' %}></script>
	<script type="text/javascript" src={% static 'Profile/js/bootstrap.min.js' %}></script>
    <style>
        .navbar{border-radius: 0px;}
    </style>
    <script type="text/javascript">
		$(function(){
	    $(".dropdown").hover(
	            function() {
	                $('.dropdown-menu', this).stop( true, true ).fadeIn("fast");
	                $(this).toggleClass('open');
	                $('b', this).toggleClass("caret caret-up");
	            },
	            function() {
	                $('.dropdown-menu', this).stop( true, true ).fadeOut("fast");
	                $(this).toggleClass('open');
	                $('b', this).toggleClass("caret caret-up");
	            });
	    });
	</script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div>
            <!-- left part -->
            <ul class="nav navbar-nav">
                <li class=""><a href={% url 'Profile:index' %}><span class="glyphicon glyphicon-user"></span> Profile</a></li>
                <li class="dropdown">
                    <a href={% url 'games:games' %}>Games <span class="glyphicon glyphicon-menu-down"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href={% url 'games:math' %}>Math game</a></li>
                        <li><a href={% url 'games:games' %}>English game</a></li>
                    </ul>
                </li>
            </ul>

            <!-- right part -->
            <ul class="nav navbar-nav navbar-right">
                <li style="margin-right: 20px;"><a href={% url 'Profile:settings' %}><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
                <li style="margin-right: 20px;"><a href={% url 'Profile:logout' %}><span class="glyphicon glyphicon-off"></span> Logout</a></li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

kids_website/Profile/templates/Profile/home.html
{% extends 'Profile/base_guest.html' %}


{% block content %}
    <style>
        * {box-sizing:border-box}
        body {font-family: Verdana,sans-serif;margin:0}
        .mySlides {display:none}

        .slideshow-container {
           position: relative;
            margin: 10%;
            width: 600px;
            height: 220px;
            margin: auto;
            margin-top: 15%;
        }

        .prev, .next {
            cursor: pointer;
            position: absolute;
            top: 40%;

            padding: 16px;
            margin-top: -22 px;
            color: white;

            font-size: 12px;
            transition: 0.6s ease;
            border-radius: 0 3px 3px 0;
        }


        .next {
            right: 0;
            border-radius: 3px 0 0 3px;
        }

        .prev:hover, .next:hover {
            background-color: rgba(0,0,0,0.8);
        }
        .numbertext {
            color: #f2f2f2;
            font-size: 12px;
            padding: 8px 12px;
            position: absolute;
            top: 0;
        }


        .dot {
            cursor:pointer;
            height: 7px;
            width: 7px;
            margin: 0 2px;
            background-color: #bbb;
            border-radius: 50%;
            display: inline-block;
            transition: background-color 0.6s ease;
            margin-top: .1%;
        }

        .active, .dot:hover {
            background-color: #717171;
        }

        .fade {
           -webkit-animation-name: fade;
           -webkit-animation-duration: 1.5s;
            animation-name: fade;
            animation-duration: 1.5s;
        }

        @-webkit-keyframes fade {
          from {opacity: .4}
          to {opacity: 1}
        }

        @keyframes fade {
          from {opacity: .4}
          to {opacity: 1}
        }



        </style>
    <div class="container">
        {% load staticfiles%}
        <div class="slideshow-container">

        <div class="mySlides fade" >
          <div class="numbertext">1 / 6</div>
          <img src={% static 'Profile/images/pro8.jpg' %} style="width:100%">
        </div>

        <div class="mySlides fade">
          <div class="numbertext">2 / 6</div>
          <img src={% static 'Profile/images/pro5.jpg' %} style="width:100%">
        </div>

        <div class="mySlides fade">
          <div class="numbertext">3 / 6</div>
          <img src={% static 'Profile/images/pro1.jpg' %} style="width:100%">
        </div>
        <div class="mySlides fade">
          <div class="numbertext">4 / 6</div>
          <img src={% static 'Profile/images/pro2.jpg' %} style="width:100%">
        </div>
        <div class="mySlides fade">
          <div class="numbertext">5 / 6</div>
          <img src={% static 'Profile/images/pro6.jpg' %} style="width:100%">
        </div>
        <div class="mySlides fade">
          <div class="numbertext">6 / 6</div>
          <img src={% static 'Profile/images/pro7.jpg' %} style="width:100%">
        </div>

        <a class="prev" onclick="plusSlides(-1)">❮</a>
        <a class="next" onclick="plusSlides(1)">❯</a>

        </div>
        <br>

        <div style="text-align:center">
          <span class="dot" onclick="currentSlide(1)"></span>
          <span class="dot" onclick="currentSlide(2)"></span>
          <span class="dot" onclick="currentSlide(3)"></span>
          <span class="dot" onclick="currentSlide(4)"></span>
          <span class="dot" onclick="currentSlide(5)"></span>
          <span class="dot" onclick="currentSlide(6)"></span>
        </div>

        <script>
        /*var slideIndex = 1;
        showSlides(slideIndex);

        function plusSlides(n) {
          showSlides(slideIndex += n);
        }

        function currentSlide(n) {
          showSlides(slideIndex = n);
        }
        }*/

        var slideIndex = 0;
        showSlides();

        function showSlides() {
            var i;
            var slides = document.getElementsByClassName("mySlides");
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }
            slideIndex++;
            if (slideIndex> slides.length) {slideIndex = 1}
            slides[slideIndex-1].style.display = "block";
            setTimeout(showSlides, 5000);
        }

        </script>
    </div>
{% endblock %}

kids_website/Profile/templates/Profile/login.html
{% extends 'Profile/base_guest.html' %}


{% block content %}
    <div class="container">
        <div class="col-md-4" style="margin-top: 30px">
            <form autocomplete="off" action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username:</label>
                    <input class="form-control" type="text" name="username" id="username" placeholder="Username" value={{ username }}>
                </div>

                <div class="form-group">
                    <label for="password">Password:</label>
                    <input class="form-control" type="password" name="password" id="password" placeholder="Password">
                </div>

                <div class="form-group">
                    <input class="btn btn-info btn-block" type="submit" value="Login">
                </div>

                {% if message %}
                <div class="form-group">
                    <p class="text-danger"><span class="glyphicon glyphicon-remove"></span> {{ message }}</p>
                </div>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

kids_website/Profile/templates/Profile/profile.html
{% extends 'Profile/base_user.html' %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                {% load staticfiles %}
                <img class="img-responsive img-thumbnail"
                     {% if user.picture %}
                     src="{{ user.picture.image }}"
                     {% else %}
                     src="{% static 'Profile/images/default.png' %}"
                     {% endif %}
                     width="165" height="165">
            </div>
            <div class="col-md-10">
                {% if user.first_name %}
                    <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                {% else %}
                    <h2>{{ user.username }}</h2>
                {% endif %}

                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Game</th>
                            <th>Score</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for score in user.score_set.all %}
                            <tr>
                                <td>{{ score.game.name }}</td>
                                <td>{{ score.value }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

kids_website/Profile/templates/Profile/register.html
{% extends 'Profile/base_guest.html' %}

{% block content %}
    <div class="container">
        <div style="margin-top: 30px">
            <form class="form-horizontal" autocomplete="off" action="" method="post">
                {% csrf_token %}
                <div class="form-group row">
                    <label class="control-label col-md-1" for="username">Username:</label>
                    <div class="col-md-8">
                        <input class="form-control" type="text" name="username" id="username" placeholder="Username can only contain letters, numbers or underscores." value={{ username }}>
                    </div>
                    {% if invalid_user %}
                    <p class="text-danger form-control-static col-md-3">
                        <span class="glyphicon glyphicon-remove"></span> {{ invalid_user }}
                    </p>
                    {% endif %}
                </div>

                <div class="form-group row">
                    <label class="control-label col-md-1" for="email">Email:</label>
                    <div class="col-md-8">
                        <input class="form-control" type="email" name="email" id="email" placeholder="Enter yout email" value={{ email }}>
                    </div>
                    {% if invalid_email %}
                    <p class="text-danger form-control-static col-md-3">
                        <span class="glyphicon glyphicon-remove"></span> {{ invalid_email }}
                    </p>
                    {% endif %}
                </div>

                <div class="form-group row">
                    <label class="control-label col-md-1" for="password">Password:</label>
                    <div class="col-md-8">
                        <input class="form-control" type="password" name="password" id="password" placeholder="Enter your password (8 characters at least)">
                    </div>
                    {% if shortpassword %}
                    <p class="text-danger form-control-static col-md-3">
                        <span class="glyphicon glyphicon-remove"></span> Short password.
                    </p>
                    {% endif %}
                </div>

                <div class="form-group row">
                    <label class="control-label col-md-1" for="confirm">Confirm:</label>
                    <div class="col-md-8">
                        <input class="form-control" type="password" name="confirmpass" id="confirm" placeholder="Confirm password">
                    </div>
                    {% if missmatch %}
                    <p class="text-danger form-control-static col-md-3">
                        <span class="glyphicon glyphicon-remove"></span> Password missmatch.
                    </p>
                    {% endif %}
                </div>

                <div class="container">
                    <div class="form-group col-md-10">
                        <button class="btn btn-success center-block" type="submit">Register</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

kids_website/Profile/templates/Profile/settings.html
{% extends 'Profile/base_user.html' %}
{% load myfilters %}


{% block content %}
    <div class="container">
        <form class="form-horizontal" autocomplete="off" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group row">
                    <label class="control-label col-md-2" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <div class="col-md-6">
                        {% if 'File' in field|klass %}
                            {{ field }}
                        {% else %}
                            {{ field | addclass:'form-control' }}
                        {% endif %}
                    </div>
                    {% if field.errors %}
                    <p class="text-danger form-control-static col-md-4">
                        <span class="glyphicon glyphicon-remove"></span> {{ field.errors.0 }}
                    </p>
                    {% endif %}
                </div>
            {% endfor %}

            <div class="container">
                <div class="form-group col-md-10">
                    <button class="btn btn-success center-block" type="submit">Submit</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}